eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
server:
  port: 9000
  servlet:
    context-path: /
spring:
  application:
    name: server‐config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/oycyqr/git.git #配置文件所在仓库
#          username: anme #登录账号
#          password: 111111 #登录密码
#          default-label: master #配置文件分支
#          search-paths: config  #配置文件所在根目录
#
#logging:
#  level:
#    org.springframework.cloud: DEBUG
#    org.springframework.boot: DEBUG
