eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 9000
  servlet:
    context-path: /
spring:
  application:
    name: springcloud‐config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oycyqr/springcloud-learning-demo.git