eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    name: springcloud‐zuul #指定服务名

zuul:
  routes:
    springcloud-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: springcloud-user #指定Eureka注册中心中的服务id
    springcloud‐article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: springcloud‐article #指定Eureka注册中心中的服务id